Experiment_name: wlasl_joint_attn2
base_lr: 0.01
batch_size: 4
config: config/WLASL/train/train_joint.yaml
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeders.feeder.Feeder
groups: 8
ignore_weights: []
keep_rate: 0.9
log_interval: 100
model: model.decouple_gcn_attn.Model
model_args:
  block_size: 41
  graph: graph.sign_42.Graph
  graph_args:
    labeling_mode: spatial
  groups: 16
  num_class: 13
  num_person: 1
  num_point: 42
model_saved_name: ./save_models/wlasl_joint_attn2
nesterov: true
num_epoch: 250
num_worker: 32
only_train_epoch: 1
only_train_part: true
optimizer: Adam
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 150
- 200
test_batch_size: 4
test_feeder_args:
  data_path: /nas/datasets/SAM-SLR-v2/data/preprocessed_data/WLASL/skeleton/val_data_joint.npy
  label_path: /nas/datasets/SAM-SLR-v2/data/preprocessed_data/WLASL/skeleton/val_label.pkl
  normalization: true
  random_mirror: false
train_feeder_args:
  data_path: /nas/datasets/SAM-SLR-v2/data/preprocessed_data/WLASL/skeleton/train_data_joint.npy
  debug: false
  is_vector: false
  label_path: /nas/datasets/SAM-SLR-v2/data/preprocessed_data/WLASL/skeleton/train_label.pkl
  normalization: true
  random_choose: true
  random_mirror: false
  random_mirror_p: 0.5
  random_shift: true
  window_size: 120
warm_up_epoch: 20
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/wlasl_joint_attn2
